"""Move processing functions.
Legal squares are generated by the piece.
"""


def move(game_board, pieces, player_turn, start, end):
    start_square = game_board.key[start]
    x1, y1 = start_square[0], start_square[1]

    end_square = game_board.key[end]
    x2, y2 = end_square[0], end_square[1]

    piece = game_board.piece_in_square(x1, y1)
    target = game_board.piece_in_square(x2, y2)

    if not piece:
        print("There's no piece in the starting square.")
        return

    if piece.color != player_turn:
        print("You can't move your opponent's piece!")
        return

    if end_square not in piece.legal_moves(game_board):
        print("That's not a legal move.")
        return

    if target:
        pieces.remove(target)

    piece.x = x2
    piece.y = y2
    piece.moves_made += 1
