"""Move processing functions.
Legal squares are generated by the piece.
"""


def move(board, pieces, player_turn, start, end):
    start_square = board.key[start]
    x1, y1 = start_square[0], start_square[1]

    end_square = board.key[end]
    x2, y2 = end_square[0], end_square[1]

    piece = board.piece_in_square(x1, y1)
    target = board.piece_in_square(x2, y2)
    king = return_king(pieces, player_turn)

    # Is there a piece?
    if not piece:
        print("There's no piece in the starting square.")
        return

    # Is it YOUR piece?
    if piece.color != player_turn:
        print("You can't move your opponent's piece!")
        return

    # Are you even allowed to do that?
    if end_square not in piece.legal_moves(board):
        print("That's not a legal move.")
        return

    # Okay then do it
    piece.x = x2
    piece.y = y2

    # Now make sure you aren't putting yourself in check by doing this. Undo if you are.
    if king.in_check(board, pieces):
        piece.x = x1
        piece.x = y1
        return

    # Otherwise: set the piece to captured and move on clean
    if target:
        del target
        # Return something?


def return_king(pieces, player_turn):
    """Returns the player's king"""
    for piece in pieces:
        if piece.color == player_turn and piece.name == 'King':
            return piece
